First version of User Guide
deepesdl/deepesdl-doc pull request #6
Opened 2022-12-19 12:36 UTC by AliceBalfanz

2022-12-19 14:50 UTC, gunbra32 requested changes

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +In the user guide you can find a description of all components belonging to
the ->this

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +There are three components of DeepESDL:
"The growing set of DeepESDL's general functionalities comprises:"

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +3. [DeepESDL datacube resources](#deepesdl-datacube-resources)
4. [DeepESDL data cube generation] (# deepesdl-datacube-generation)

Here, we describe our general approach of data cube generation and refer to i) example notebooks for ad hoc generation by users and ii) recipes for published, reproducible cubes and the cube specification.

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +the JupyterLab environment as deployed on the DeepESDL system.
as offered by DeepESDL.

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> + - The [xcube documentation](https://xcube.readthedocs.io/): user
memo: xcube documentation to be updated.

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +DeepESDL uses a GitHub to authenticate, so if you are already registered as a
DeepESDL uses GitHub to authenticate
User must be registered first. We thus need a sentence lie: Before first usage, we will have to register you with the system. To this end, we kindly ask you to duly compete the registration dialogue (link)/write as an email/...

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +your current task; it might not always require the strongest computational
strongest -> all available computational resources.

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +After choosing your environment, you will see a progress bar appear for a few
appearing

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +A user JupyterLab profiles provides a particular combination of pre-installed
A JupyterLab profile

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +If you have already started your session and need to change JupyterLab profiles,
profile

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +The DeepESDL xcube viewer is reachable via
reachable at

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +https://viewer.earthsystemdatalab.net/ .
https://viewer.earthsystemdatalab.net

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +The viewer currently shows public datasets, and later will allow to see
contains public datasets only, but will later also provide user cubes when logged in.

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +JupyterLab.
The login will be the same as for the DeepESDL JupyterLab.

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +free of charge. They come without any warranty, neither from the owners,
and allowing us to process, and redistribute them,

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +the DeepESDL team or ESA.
All datacubes generated and distributed by DeepESDL come without any warranty, neither from the owners, from the DeepESDL, nor form ESA.

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +At ingestion into the DeepESDL, all data sets are transformed in space and time
data sets are typically transformed ...

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +the original. If you are looking for the original data, please follow the links
the original data.

2022-12-19 14:50 UTC, gunbra32 commented on docs/guide/user-guide.md
> +
add 4 section here (see above for details).

2022-12-20 08:56 UTC, forman commented on docs/guide/user-guide.md
> +3. [DeepESDL datacube resources](#deepesdl-datacube-resources)
```suggestion
3. [DeepESDL datacubes](#deepesdl-datacube-resources)
```

To me _Datacube resources_  sounds like resources attached to or required for datacubes.

2022-12-20 08:56 UTC, forman commented on docs/guide/user-guide.md
> +# DeepESDL datacube resources
```suggestion
# DeepESDL datacubes
```

2022-12-20 08:56 UTC, forman commented on docs/guide/user-guide.md
> +[‘Further information’ section](#further-information).
```suggestion
section [Further Information](#further-information).
```

2022-12-20 08:56 UTC, forman commented on docs/guide/user-guide.md
> +In the user guide you can find a description of all components belonging to
```suggestion
This user guide helps you getting started with the main components of 
```

2022-12-20 08:56 UTC, forman commented on docs/guide/user-guide.md
> +resources needs of your team. Please select an adequate JupyterLab profiles for
```suggestion
resources needs of your team. Please select a suitable profile for 
```

2022-12-20 08:56 UTC, forman commented on docs/guide/user-guide.md
> +### Choosing a JupyterLab profile
Note, you already discussed above which profile to choose.

2022-12-20 08:56 UTC, forman commented on docs/guide/user-guide.md
> +you can do this by selecting ‘Hub control panel’ from the ‘File’ menu within
```suggestion
you can do this by selecting *Hub control panel* from the *File* menu within
```

To me, putting phrases in quotation marks is indicating either quotes, code string literals, verbatim speech, or ironic meaning. Therefore I prefer highlighting of UI elements via font style.

2022-12-20 08:56 UTC, forman commented on docs/guide/user-guide.md
> +https://xcube.readthedocs.io/en/latest/viewer.html#functionality
```suggestion
For a more detailed description of the viewer functionality, please refer to a dedicated section in the
[xcube documentation](https://xcube.readthedocs.io/en/latest/viewer.html#functionality).
```

2022-12-20 10:35 UTC, AliceBalfanz commented on docs/guide/user-guide.md
> +If you have already started your session and need to change JupyterLab profiles,
```suggestion
If you have already started your session and need to change the JupyterLab profile, 
```

2022-12-20 10:52 UTC, AliceBalfanz commented on docs/guide/user-guide.md
> +cubes when logged in. TThe login will be the same as for the DeepESDL JupyterLab.
```suggestion
cubes when logged in. The login will be the same as for the DeepESDL JupyterLab.
```

2022-12-20 10:56 UTC, AliceBalfanz commented on docs/guide/user-guide.md
> +recipe structure of the provided datasets within DeepESDL:
```suggestion
recipe structure of the provided datasets within DeepESDL.
```

2022-12-20 12:07 UTC, gunbra32 requested changes

2022-12-20 12:07 UTC, gunbra32 commented on docs/guide/user-guide.md
> +be updated too, hereby creating considerable maintenance effort. In addition,
```suggestion
be updated too, hereby creating considerable maintenance effort and risks for the integrity of the data cube. In addition,
```

2022-12-20 12:07 UTC, gunbra32 commented on docs/guide/user-guide.md
> +casein an optimal way. By definition, they do not allow for streamlined and
```suggestion
case in an optimal way. By definition, they do not allow for streamlined and 
```

2022-12-20 12:24 UTC, AliceBalfanz commented on docs/guide/user-guide.md
> +cube, a dedicated JSON format is created that fully describes the target
Further below in the git-repo link

2022-12-20 14:41 UTC, merged